import { Inter, Roboto_Condensed } from "next/font/google";
import "./globals.css";
import Animation from "./components/Animation/Animation";

const robotCondensed = Roboto_Condensed({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto-condensed",
});

const inter = Inter({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-inter",
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${robotCondensed.variable} ${inter.variable} antialiased`}
      >
        <Animation />
        {children}
      </body>
    </html>
  );
}
